### PR TITLE
Deployment Cleanup

### PR DESCRIPTION
**Pull request by aniewielska**
What do you think of 2-step deployment process? (Plus I tested it only for OpenStack with Ingress with/without TLS and OpenShift with Router, so it needs tests on 2 remaining platforms)

### CODE REVIEW

**Comment by psafont** [comment]
The service doesn't seem to be properly exposed (Maybe I missed a step?):

```
$ kubectl get services tesk-api
NAME       TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
tesk-api   NodePort   10.100.201.222   <none>        8080:30810/TCP   51s
```

```
$ kubectl expose deployment tesk-api --type=NodePort
Error from server (AlreadyExists): services "tesk-api" already exists
```

```
$ ping (minikube service tesk-api --url)
ping: http://192.168.99.100:30810: Name or service not known
```

```
$ kubectl describe deployment tesk-api
Name:                   tesk-api
Namespace:              default
CreationTimestamp:      Wed, 11 Jul 2018 09:09:26 +0100
Labels:                 app=tesk-api
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=tesk-api
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=tesk-api
  Service Account:  taskmaster
  Containers:
   tesk-api:
    Image:      eu.gcr.io/tes-wes/tesk-api:v0.4
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      TESK_API_TASKMASTER_IMAGE_VERSION:         v0.4
      TESK_API_TASKMASTER_FILER_IMAGE_VERSION:   v0.4
      TESK_API_K8S_NAMESPACE:                    default
      TESK_API_TASKMASTER_SERVICE_ACCOUNT_NAME:  taskmaster
      TESK_API_TASKMASTER_FTP_SECRET_NAME:       ftp-secret
      TESK_API_AUTHORISATION_ENV_SUBGROUP:       EBI
      SPRING_PROFILES_ACTIVE:                    noauth
      TESK_API_SWAGGER_OAUTH_CLIENT_ID:          <set to the key 'id' in secret 'oauth-client-secret'>  Optional: true
    Mounts:                                      <none>
  Volumes:                                       <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   tesk-api-7dc6459dfc (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  1m    deployment-controller  Scaled up replica set tesk-api-7dc6459dfc to 1
```
I've tried with kubernetes 1.9.4 and 1.10.5 (1.11.0 doesn't work)

**Comment by psafont** [comment]
It took quite a while to expose the port, but it works, instructions are fine

**Comment by aniewielska** [comment]
I managed to install minikube on Win10 and for me it worked, too (without delay). I will have a look at 1.11

**Comment by psafont** [comment]
I meant that kubernetes 1.11 is not yet supported by minikube

**Pull request merged**
